//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotExtensions.Memory.Internal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotExtensions.Memory.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DotExtensions_Tests_AoT_Intro {
            get {
                return ResourceManager.GetString("DotExtensions.Tests.AoT.Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory must not contain chars or strings with whitespace..
        /// </summary>
        internal static string Exceptions_Argument_WhiteSpace_Memory {
            get {
                return ResourceManager.GetString("Exceptions.Argument.WhiteSpace.Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span must not contain chars or strings with whitespace..
        /// </summary>
        internal static string Exceptions_Argument_WhiteSpace_Span {
            get {
                return ResourceManager.GetString("Exceptions.Argument.WhiteSpace.Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory must not be empty for this operation to be performed successfully..
        /// </summary>
        internal static string Exceptions_InvalidOperation_EmptyMemory {
            get {
                return ResourceManager.GetString("Exceptions.InvalidOperation.EmptyMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span must not be empty for this operation to be performed successfully..
        /// </summary>
        internal static string Exceptions_InvalidOperation_EmptySpan {
            get {
                return ResourceManager.GetString("Exceptions.InvalidOperation.EmptySpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination span length is shorter than the source span..
        /// </summary>
        internal static string Exceptions_Spans_Copy_DestinationShorterThanSource {
            get {
                return ResourceManager.GetString("Exceptions.Spans.Copy.DestinationShorterThanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination span length is smaller than start index + length..
        /// </summary>
        internal static string Exceptions_Spans_Copy_DestinationSmallerThanIndex {
            get {
                return ResourceManager.GetString("Exceptions.Spans.Copy.DestinationSmallerThanIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the keys span and values span do not match..
        /// </summary>
        internal static string Exceptions_Spans_Sorts_LengthMismatch {
            get {
                return ResourceManager.GetString("Exceptions.Spans.Sorts.LengthMismatch", resourceCulture);
            }
        }
    }
}
