version = 1

[[annotations]]
path = ["**/*.csproj", "**/*.csproj.DotSettings", "**/*.sln", "**/*.slnx", "**/*.resx"]
style= "html"
SPDX-FileCopyrightText = "Copyright (c) 2025 Alastair Lundy"
SPDX-License-Identifier = "MIT"
precedence="override"
