//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotExtensions.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotExtensions.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count cannot be 0 or less. Provided count was {x}..
        /// </summary>
        internal static string Exceptions_Count_LessThanZero {
            get {
                return ResourceManager.GetString("Exceptions.Count.LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{directory}&apos; could not be found or does not exist..
        /// </summary>
        internal static string Exceptions_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions.DirectoryNotFound", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Cannot get the directory of a file ({0}) that does not exist..
        /// </summary>
        internal static string Exceptions_Directory_FileArgumentNotFound {
            get {
                return ResourceManager.GetString("Exceptions.Directory.FileArgumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration of elements yielded zero items. The sequence was empty. .
        /// </summary>
        internal static string Exceptions_Enumerables_InvalidOperation_EmptySequence {
            get {
                return ResourceManager.GetString("Exceptions.Enumerables.InvalidOperation.EmptySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot split an empty enumerable..
        /// </summary>
        internal static string Exceptions_EnumerablesSplit_Empty {
            get {
                return ResourceManager.GetString("Exceptions.EnumerablesSplit.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{file}&apos; could not be found or does not exist..
        /// </summary>
        internal static string Exceptions_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find directory with file path of {x}..
        /// </summary>
        internal static string Exceptions_IO_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions.IO.DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyValuePair not found within the collection.
        /// </summary>
        internal static string Exceptions_KeyValuePairNotFound {
            get {
                return ResourceManager.GetString("Exceptions.KeyValuePairNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invalid Unix Numeric file permission notation of {x} was provided..
        /// </summary>
        internal static string Exceptions_Permissions_Unix_InvalidNumericNotation {
            get {
                return ResourceManager.GetString("Exceptions.Permissions.Unix.InvalidNumericNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invalid Unix Symbolic file permission notation of {x} was provided..
        /// </summary>
        internal static string Exceptions_Permissions_Unix_InvalidSymbolicNotation {
            get {
                return ResourceManager.GetString("Exceptions.Permissions.Unix.InvalidSymbolicNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot request more elements than the target span contains..
        /// </summary>
        internal static string Exceptions_Span_Request_CountTooLarge {
            get {
                return ResourceManager.GetString("Exceptions.Span.Request.CountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot skip more elements than the target span contains..
        /// </summary>
        internal static string Exceptions_Span_SkipCountTooLarge {
            get {
                return ResourceManager.GetString("Exceptions.Span.SkipCountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be empty.
        /// </summary>
        internal static string Exceptions_ThrowIfNullOrEmpty_Empty {
            get {
                return ResourceManager.GetString("Exceptions.ThrowIfNullOrEmpty.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {x} Not Found within Key Value Pair.
        /// </summary>
        internal static string Exceptions_ValueNotFound {
            get {
                return ResourceManager.GetString("Exceptions.ValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version string: &apos;{0}&apos;.
        /// </summary>
        internal static string Exceptions_VersionParsing_InvalidVersionString {
            get {
                return ResourceManager.GetString("Exceptions.VersionParsing.InvalidVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string does not contain a valid version..
        /// </summary>
        internal static string Exceptions_Versions_GracefulParse_NoDigits {
            get {
                return ResourceManager.GetString("Exceptions.Versions.GracefulParse.NoDigits", resourceCulture);
            }
        }
    }
}
