//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.DotExtensions.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AlastairLundy.DotExtensions.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_ValueNotFound {
            get {
                return ResourceManager.GetString("Exceptions.ValueNotFound", resourceCulture);
            }
        }
        
        internal static string Exceptions_KeyValuePairNotFound {
            get {
                return ResourceManager.GetString("Exceptions.KeyValuePairNotFound", resourceCulture);
            }
        }
        
        internal static string Exceptions_Span_SkipCountTooLarge {
            get {
                return ResourceManager.GetString("Exceptions.Span.SkipCountTooLarge", resourceCulture);
            }
        }
        
        internal static string Exceptions_EnumerablesSplit_Empty {
            get {
                return ResourceManager.GetString("Exceptions.EnumerablesSplit.Empty", resourceCulture);
            }
        }
        
        internal static string Exceptions_IO_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions.IO.DirectoryNotFound", resourceCulture);
            }
        }
        
        internal static string Exceptions_Enumerables_InvalidOperation_EmptySequence {
            get {
                return ResourceManager.GetString("Exceptions.Enumerables.InvalidOperation.EmptySequence", resourceCulture);
            }
        }
        
        internal static string Exceptions_Count_LessThanZero {
            get {
                return ResourceManager.GetString("Exceptions.Count.LessThanZero", resourceCulture);
            }
        }
        
        internal static string Exceptions_Span_Request_CountTooLarge {
            get {
                return ResourceManager.GetString("Exceptions.Span.Request.CountTooLarge", resourceCulture);
            }
        }
        
        internal static string Exceptions_ThrowIfNullOrEmpty_Empty {
            get {
                return ResourceManager.GetString("Exceptions.ThrowIfNullOrEmpty.Empty", resourceCulture);
            }
        }
    }
}
